services:
  caddy:
    build:
      context: .
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
